### ISSUE TITLE
org.freedesktop.Platform.GL.default branch 22.08 is end-of-life

### ISSUE THREAD

**Issue by BMiZEL** [flathub/app.organicmaps.desktop#86] opened 2024-11-27 05:40 UTC
Hi there, f.y.i.

"Info: (pinned) runtime org.freedesktop.Platform.GL.default branch 22.08 is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version."

**Comment by Ferenc-** [comment] 2024-11-27 09:02
This is a dependency of `org.kde.Platform branch 6.6`  so in essence this is a duplicate of https://github.com/flathub/app.organicmaps.desktop/issues/83

**Closed by Ferenc-** 2024-11-27 09:02 UTC
