### ISSUE TITLE
Assertion failed, when trying to get a route

### ISSUE THREAD

**Issue by Ferenc-** [flathub/app.organicmaps.desktop#3] opened 2022-05-02 13:54 UTC
This time I am trying this flatpak on Xorg on an x86_64 desktop.
I have one map downloaded, and whenever I try to get a route between two points (IMHO within that map), I get an assertion failure:

```
LOG TID(2) INFO     0.307428 search/processor.cpp:377 LoadCitiesBoundaries() Loaded cities boundaries
LOG TID(5) INFO      36.9847 routing/async_router.cpp:341 CalculateRoute() Calculating the route. checkpoints: Checkpoints(ms::LatLon(53.3844461, 7.41494737); ms::LatLon(53.3136058, 7.51270854); passed: 0) startDirection: m2::Point<d>(0, 0) router name: astar-bidirectional-Car
LOG TID(5) INFO      36.9849 routing/index_router.cpp:961 MakeWorldGraph() Avoid next roads: RoutingOptions: {}
LOG TID(5) WARNING    36.991 storage/storage.cpp:1847 GetParentIdFor() CountryId = WorldCoasts not found in m_countries.
LOG TID(5) INFO       37.378 routing/index_graph_loader.cpp:172 CreateIndexGraph() routing section for Germany_Lower Saxony_Oldenburg loaded in 0.382271 seconds
LOG TID(5) INFO      37.3885 routing/index_router.cpp:732 CalculateSubroute() Routing in mode: Joints
LOG TID(5) INFO      37.4356 base/timer.cpp:224 ~ScopedTimerWithLog() Route build time: 46 ms
/usr/include/c++/11.2.0/bits/stl_vector.h:1063: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) const [with _Tp = routing::Edge; _Alloc = std::allocator<routing::Edge>; std::vector<_Tp, _Alloc>::const_reference = const routing::Edge&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```

**Comment by fgaz** [comment] 2022-05-02 16:32
Duplicate of #2

**Closed by fgaz** 2022-05-02 16:32 UTC

**Comment by fgaz** [comment] 2022-05-02 16:34
By the way if you manage to get a stack trace please post it in #2!
